name: Deploy to Production

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build-push-image.yaml
    permissions:
      contents: read
      packages: write
    with:
      tag: ${{ github.event.release.tag_name }}
      additional_tag: latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      NS: relay
      CLUSTER: plugins-prod-k8s
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_CI_TOKEN }}

      - name: Get kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ env.CLUSTER }}

      - name: Update deployment image
        run: |
          sed -i 's|image: busybox|image: ghcr.io/vultisig/vultisig-relay/router:${{ github.event.release.tag_name }}|g' deploy/01_router.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl -n ${{ env.NS }} apply -f deploy/01_router.yaml
          kubectl -n ${{ env.NS }} apply -f deploy/prod/

      - name: Wait for rollout
        run: |
          kubectl -n ${{ env.NS }} rollout status deployment/router --timeout=300s
