name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    uses: ./.github/workflows/build-push-image.yaml
    with:
      tag: dev-${{ github.sha }}
      additional_tag: dev-latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_CI_TOKEN }}

      - name: Get kubeconfig
        run: doctl kubernetes cluster kubeconfig save plugins-dev-k8s

      - name: Update deployment image
        run: |
          sed -i 's|image: busybox|image: ghcr.io/vultisig/router:dev-${{ github.sha }}|g' deploy/01_router.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deploy/01_router.yaml

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/router -n router --timeout=300s
